# GENERATED by bin/bprm_stubs from docs/bprm/scenarios.tsv (rpms-ux 7f076114c7126241b12c06f790a10bc93ea70442). Do not edit.
# A scenario leaves this file by being written, with the same tag, in
# features/bprm_twin/w01_*/ and rerunning bin/bprm_stubs.
@bprm_twin @bprm_stub @W01
Feature: W01 Patient Registration: scenarios no lakeraven-ehr screen drives yet

  @S-REG-01.3
  Scenario: S-REG-01.3 Find the patient before registering
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-01 Find the patient before registering"
    And the front desk clerk is signed on
    And "a patient whose chart at this facility is inactive or deleted"
    When "I search"
    Then "the patient is listed with that chart status, so I do not mistake them for an active patient"

  @S-REG-01.4
  Scenario: S-REG-01.4 Find the patient before registering
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-01 Find the patient before registering"
    And the front desk clerk is signed on
    And "a deceased patient"
    When "I search"
    Then "the patient is listed as deceased"

  @S-REG-01.5
  Scenario: S-REG-01.5 Find the patient before registering
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-01 Find the patient before registering"
    And the front desk clerk is signed on
    And "a patient registered at another facility and not at this one"
    When "I open their registration"
    Then "I am asked for a health record number at this facility before anything else, and until one is filed in the HEALTH RECORD NO. multiple (#9000001.41) of IHS PATIENT (#9000001) the record cannot be edited here"

  @S-REG-01.6
  Scenario: S-REG-01.6 Find the patient before registering
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-01 Find the patient before registering"
    And the front desk clerk is signed on
    And "I have the patient open at the front desk"
    When "I send them to the EHR"
    Then "the patient context for my user is set to this patient, so the EHR on my workstation opens on them"

  @S-REG-02.3
  Scenario: S-REG-02.3 Register a new patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-02 Register a new patient"
    And the front desk clerk is signed on
    And "a patient already on file with the same name, date of birth and sex"
    When "I enter the new patient's name, date of birth and sex"
    Then "I am shown the possible matches, with their chart numbers, before anything is filed, and I can open one of them instead of registering"

  @S-REG-02.4
  Scenario: S-REG-02.4 Register a new patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-02 Register a new patient"
    And the front desk clerk is signed on
    And "a name that is not `LAST,FIRST MIDDLE`, or shorter than 3 or longer than 30 characters"
    When "I save"
    Then "the registration is refused and names the format"

  @S-REG-02.5
  Scenario: S-REG-02.5 Register a new patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-02 Register a new patient"
    And the front desk clerk is signed on
    And "a date of birth in the future, or before 1871"
    When "I save"
    Then "the registration is refused"

  @S-REG-02.6
  Scenario: S-REG-02.6 Register a new patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-02 Register a new patient"
    And the front desk clerk is signed on
    And "no social security number and no reason for having none"
    When "I save"
    Then "the registration is refused and asks for the reason"

  @S-REG-02.7
  Scenario: S-REG-02.7 Register a new patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-02 Register a new patient"
    And the front desk clerk is signed on
    And "a social security number that is not nine digits"
    When "I save"
    Then "the registration is refused and names the format"

  @S-REG-02.8
  Scenario: S-REG-02.8 Register a new patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-02 Register a new patient"
    And the front desk clerk is signed on
    And "a social security number already on another patient in PATIENT (#2)"
    When "I save"
    Then "the registration is refused and nothing is filed"

  @S-REG-02.9
  Scenario: S-REG-02.9 Register a new patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-02 Register a new patient"
    And the front desk clerk is signed on
    And "a health record number already assigned to another patient at this facility, in any of its leading-zero or temporary forms"
    When "I save"
    Then "the registration is refused and names the number"

  @S-REG-02.10
  Scenario: S-REG-02.10 Register a new patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-02 Register a new patient"
    And the front desk clerk is signed on
    And "a health record number that is not 1 to 6 characters in the chart-number format"
    When "I save"
    Then "the registration is refused"

  @S-REG-02.11
  Scenario: S-REG-02.11 Register a new patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-02 Register a new patient"
    And the front desk clerk is signed on
    And "I have not said whether the patient received the notice of privacy practices, or whether they are a veteran"
    When "I save"
    Then "the registration is refused and names what is missing"

  @S-REG-02.12
  Scenario: S-REG-02.12 Register a new patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-02 Register a new patient"
    And the front desk clerk is signed on
    And "this facility's REGISTRATION PARAMETERS (#9009061) make the street address, city, state or zip code mandatory"
    When "I save without one of them"
    Then "the registration is refused and names the field"

  @S-REG-02.13
  Scenario: S-REG-02.13 Register a new patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-02 Register a new patient"
    And the front desk clerk is signed on
    And "no primary language, or no community of residence and date moved there"
    When "I save"
    Then "the registration is refused and names the value"

  @S-REG-02.14
  Scenario: S-REG-02.14 Register a new patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-02 Register a new patient"
    And the front desk clerk is signed on
    And "a complete registration"
    When "I save"
    Then "IHS PATIENT (#9000001) holds today as the date established and me as the establishing user and the user of the last update, and the patient's registration event is raised for the packages that listen for it"

  @S-REG-02.15
  Scenario: S-REG-02.15 Register a new patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-02 Register a new patient"
    And the front desk clerk is signed on
    And "I hold none of the keys that allow registering a patient (AGZMGR, AGZMENU, XUPROG, XUPROGMODE)"
    When "I open registration"
    Then "I cannot add a patient"

  @S-REG-03.1
  Scenario: S-REG-03.1 Record eligibility and insurance
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-03 Record eligibility and insurance"
    And the front desk clerk is signed on
    And "a registered patient with Medicaid"
    When "I add the Medicaid number and eligibility dates"
    Then "the eligibility shows on the patient and is in force on today's date"

  @S-REG-03.2
  Scenario: S-REG-03.2 Record eligibility and insurance
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-03 Record eligibility and insurance"
    And the front desk clerk is signed on
    And "eligibility that has lapsed"
    When "I check the patient in"
    Then "I am warned before the visit is created"

  @S-REG-04.1
  Scenario: S-REG-04.1 Open a sensitive patient's record
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-04 Open a sensitive patient's record"
    And the front desk clerk is signed on
    And "a patient whose record is marked sensitive"
    When "I open them and accept that I have a need to know"
    Then "the record opens and DG SECURITY LOG (#38.1) holds my access to the patient with the date, my user and the registration option"

  @S-REG-04.2
  Scenario: S-REG-04.2 Open a sensitive patient's record
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-04 Open a sensitive patient's record"
    And the front desk clerk is signed on
    And "a patient whose record is marked sensitive"
    When "I decline the warning"
    Then "the record does not open and nothing is logged"

  @S-REG-04.3
  Scenario: S-REG-04.3 Open a sensitive patient's record
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-04 Open a sensitive patient's record"
    And the front desk clerk is signed on
    And "a patient whose record is my own"
    When "I try to open it"
    Then "I am refused and the record does not open"

  @S-REG-04.4
  Scenario: S-REG-04.4 Open a sensitive patient's record
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-04 Open a sensitive patient's record"
    And the front desk clerk is signed on
    And "a patient I am restricted from, or my own user has no social security number on file"
    When "I try to open them"
    Then "I am refused and told why, and the record does not open"

  @S-REG-04.5
  Scenario: S-REG-04.5 Open a sensitive patient's record
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-04 Open a sensitive patient's record"
    And the front desk clerk is signed on
    And "a patient whose record is marked for a warning only"
    When "I open them"
    Then "I am warned and the record opens without a log entry"

  @S-REG-05.1
  Scenario: S-REG-05.1 Register a patient quickly from scheduling
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-05 Register a patient quickly from scheduling"
    And the scheduler is signed on
    And "a caller with no chart"
    When "I enter name, date of birth, sex and social security number and ask for a chart number to be generated"
    Then "the patient exists in PATIENT (#2) and IHS PATIENT (#9000001) with me as the user who entered them, and the HEALTH RECORD NO. multiple (#9000001.41) holds a temporary number for this facility"

  @S-REG-05.2
  Scenario: S-REG-05.2 Register a patient quickly from scheduling
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-05 Register a patient quickly from scheduling"
    And the scheduler is signed on
    And "a caller with no chart and a chart number I have been given"
    When "I enter it instead of asking for one"
    Then "the HEALTH RECORD NO. multiple (#9000001.41) holds that number for this facility"

  @S-REG-05.3
  Scenario: S-REG-05.3 Register a patient quickly from scheduling
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-05 Register a patient quickly from scheduling"
    And the scheduler is signed on
    And "a patient already on file with the same name, date of birth and sex"
    When "I enter the caller's details"
    Then "I am shown the possible matches and can pick one to book instead of registering again"

  @S-REG-05.4
  Scenario: S-REG-05.4 Register a patient quickly from scheduling
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-05 Register a patient quickly from scheduling"
    And the scheduler is signed on
    And "no social security number and no reason for having none, or a number already on another patient"
    When "I save"
    Then "it is refused and nothing is filed"

  @S-REG-05.5
  Scenario: S-REG-05.5 Register a patient quickly from scheduling
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-05 Register a patient quickly from scheduling"
    And the scheduler is signed on
    And "a chart number already assigned to another patient at this facility"
    When "I save"
    Then "it is refused and names the number"

  @S-REG-05.6
  Scenario: S-REG-05.6 Register a patient quickly from scheduling
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-05 Register a patient quickly from scheduling"
    And the scheduler is signed on
    And "I do not hold the scheduling registration key (SDZREGMENU)"
    When "I search and find no match"
    Then "I am not offered to register the caller"

  @S-REG-06.1
  Scenario: S-REG-06.1 Give a patient from another facility a chart here
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-06 Give a patient from another facility a chart here"
    And the front desk clerk is signed on
    And "a patient with a chart at another facility and none at this one"
    When "I add a health record number for this facility"
    Then "the HEALTH RECORD NO. multiple (#9000001.41) of IHS PATIENT (#9000001) holds the number under this facility, and the other facility's number is unchanged"

  @S-REG-06.2
  Scenario: S-REG-06.2 Give a patient from another facility a chart here
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-06 Give a patient from another facility a chart here"
    And the front desk clerk is signed on
    And "a patient who already has a chart at this facility"
    When "I try to add another"
    Then "I am told they are already registered here and nothing is filed"

  @S-REG-06.3
  Scenario: S-REG-06.3 Give a patient from another facility a chart here
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-06 Give a patient from another facility a chart here"
    And the front desk clerk is signed on
    And "a number already assigned to another patient at this facility, in any of its leading-zero or temporary forms"
    When "I save"
    Then "it is refused and names the number"

  @S-REG-06.4
  Scenario: S-REG-06.4 Give a patient from another facility a chart here
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-06 Give a patient from another facility a chart here"
    And the front desk clerk is signed on
    And "I hold the view-only key (AGZVIEWONLY) or not the registration key (AGZMENU)"
    When "I open a patient from another facility"
    Then "I cannot add a chart number here"

  @S-REG-07.1
  Scenario: S-REG-07.1 Record tribe, blood quantum and eligibility
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-07 Record tribe, blood quantum and eligibility"
    And the front desk clerk is signed on
    And "a tribal member"
    When "I record eligibility status, classification, tribe of membership, Indian blood quantum, tribe quantum and enrollment number"
    Then "IHS PATIENT (#9000001) holds those values"

  @S-REG-07.2
  Scenario: S-REG-07.2 Record tribe, blood quantum and eligibility
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-07 Record tribe, blood quantum and eligibility"
    And the front desk clerk is signed on
    And "a patient with a second tribe"
    When "I add it with its quantum"
    Then "the OTHER TRIBE multiple of IHS PATIENT (#9000001) holds that tribe and quantum"

  @S-REG-07.3
  Scenario: S-REG-07.3 Record tribe, blood quantum and eligibility
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-07 Record tribe, blood quantum and eligibility"
    And the front desk clerk is signed on
    And "an eligibility status that needs reasons"
    When "I add each reason"
    Then "the patient's ELIGIBILITY MODIFIERS multiple (#9000001.03401) holds one entry per reason, each pointing at ELIGIBILITY MODIFIERS (#9000030), and no reason twice"

  @S-REG-07.4
  Scenario: S-REG-07.4 Record tribe, blood quantum and eligibility
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-07 Record tribe, blood quantum and eligibility"
    And the front desk clerk is signed on
    And "a classification of Indian or Alaska Native"
    When "I save with an eligibility status of ineligible, or a tribe of NON-INDIAN"
    Then "it is refused and says which value contradicts the other"

  @S-REG-07.5
  Scenario: S-REG-07.5 Record tribe, blood quantum and eligibility
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-07 Record tribe, blood quantum and eligibility"
    And the front desk clerk is signed on
    And "an eligibility status of ineligible, or a classification of non-Indian or other"
    When "I save with a tribe other than NON-INDIAN"
    Then "it is refused and asks for NON-INDIAN"

  @S-REG-07.6
  Scenario: S-REG-07.6 Record tribe, blood quantum and eligibility
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-07 Record tribe, blood quantum and eligibility"
    And the front desk clerk is signed on
    And "a blood quantum that is not a fraction or one of FULL, NONE, UNKNOWN or UNSPECIFIED, or a fraction over 1"
    When "I save"
    Then "it is refused and names the form"

  @S-REG-07.7
  Scenario: S-REG-07.7 Record tribe, blood quantum and eligibility
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-07 Record tribe, blood quantum and eligibility"
    And the front desk clerk is signed on
    And "a tribe of NON-INDIAN"
    When "I save a blood quantum other than NONE or UNKNOWN"
    Then "it is refused; and given any other tribe, a quantum of NONE or UNKNOWN is refused"

  @S-REG-07.8
  Scenario: S-REG-07.8 Record tribe, blood quantum and eligibility
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-07 Record tribe, blood quantum and eligibility"
    And the front desk clerk is signed on
    And "a tribe quantum, or another tribe's quantum, greater than the Indian blood quantum"
    When "I save"
    Then "it is refused"

  @S-REG-07.9
  Scenario: S-REG-07.9 Record tribe, blood quantum and eligibility
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-07 Record tribe, blood quantum and eligibility"
    And the front desk clerk is signed on
    And "another tribe that is the tribe of membership, or listed twice"
    When "I save"
    Then "it is refused"

  @S-REG-08.1
  Scenario: S-REG-08.1 Record the emergency contact and next of kin
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-08 Record the emergency contact and next of kin"
    And the front desk clerk is signed on
    And "a patient"
    When "I record an emergency contact's name, relationship, address and phones"
    Then "PATIENT (#2) holds the emergency contact's name, address and phones and IHS PATIENT (#9000001) holds the relationship; the same holds for the next of kin"

  @S-REG-08.2
  Scenario: S-REG-08.2 Record the emergency contact and next of kin
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-08 Record the emergency contact and next of kin"
    And the front desk clerk is signed on
    And "an emergency contact on file with an address and phones"
    When "I change the contact's name and save nothing else"
    Then "the previous contact's address and phones are cleared, not carried over to the new person"

  @S-REG-08.3
  Scenario: S-REG-08.3 Record the emergency contact and next of kin
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-08 Record the emergency contact and next of kin"
    And the front desk clerk is signed on
    And "a contact name that is not `LAST,FIRST MIDDLE,SUFFIX`, or shorter than 3 characters"
    When "I save"
    Then "it is refused and names the format"

  @S-REG-08.4
  Scenario: S-REG-08.4 Record the emergency contact and next of kin
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-08 Record the emergency contact and next of kin"
    And the front desk clerk is signed on
    And "a relationship, address or phone for a contact but no name"
    When "I save"
    Then "it is refused and asks for the name"

  @S-REG-09.1
  Scenario: S-REG-09.1 Record family and household information
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-09 Record family and household information"
    And the front desk clerk is signed on
    And "a minor patient"
    When "I record the father's name, the mother's maiden name, their relationship, phones, employer, email and place of birth"
    Then "PATIENT (#2) holds the two names and IHS PATIENT (#9000001) holds the rest"

  @S-REG-09.2
  Scenario: S-REG-09.2 Record family and household information
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-09 Record family and household information"
    And the front desk clerk is signed on
    And "a patient with a guardian who is not a parent"
    When "I record the guardian's name and relationship, and a second guardian if there is one"
    Then "IHS PATIENT (#9000001) holds each guardian with their relationship and contact details"

  @S-REG-09.3
  Scenario: S-REG-09.3 Record family and household information
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-09 Record family and household information"
    And the front desk clerk is signed on
    And "a guardian's relationship but no name, or a name but no relationship"
    When "I save"
    Then "it is refused and names what is missing"

  @S-REG-09.4
  Scenario: S-REG-09.4 Record family and household information
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-09 Record family and household information"
    And the front desk clerk is signed on
    And "a parent or guardian name that is not `LAST,FIRST MIDDLE,SUFFIX`"
    When "I save"
    Then "it is refused and names the format"

  @S-REG-09.5
  Scenario: S-REG-09.5 Record family and household information
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-09 Record family and household information"
    And the front desk clerk is signed on
    And "a household size of 100 or more, or an income of 0 or of 10,000,000 or more"
    When "I save"
    Then "it is refused"

  @S-REG-09.6
  Scenario: S-REG-09.6 Record family and household information
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-09 Record family and household information"
    And the front desk clerk is signed on
    And "this facility requires the household income"
    When "I save without the income or its period"
    Then "it is refused and names the value"

  @S-REG-10.1
  Scenario: S-REG-10.1 Record the patient's languages
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-10 Record the patient's languages"
    And the front desk clerk is signed on
    And "a patient"
    When "I record their primary language, preferred language, English proficiency and other languages"
    Then "the languages multiple of IHS PATIENT (#9000001) holds a new entry dated today with those values and one line per other language, and earlier entries are kept"

  @S-REG-10.2
  Scenario: S-REG-10.2 Record the patient's languages
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-10 Record the patient's languages"
    And the front desk clerk is signed on
    And "a primary or other language of English"
    When "I save without an English proficiency, or with a proficiency of not at all"
    Then "it is refused"

  @S-REG-10.3
  Scenario: S-REG-10.3 Record the patient's languages
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-10 Record the patient's languages"
    And the front desk clerk is signed on
    And "a primary language other than English"
    When "I save without saying whether an interpreter is needed"
    Then "it is refused and asks for it"

  @S-REG-10.4
  Scenario: S-REG-10.4 Record the patient's languages
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-10 Record the patient's languages"
    And the front desk clerk is signed on
    And "an other language that is the primary language, or listed twice"
    When "I save"
    Then "it is refused"

  @S-REG-10.5
  Scenario: S-REG-10.5 Record the patient's languages
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-10 Record the patient's languages"
    And the front desk clerk is signed on
    And "a preferred language that is neither the primary language nor one of the other languages"
    When "I save"
    Then "I am warned and may still save"

  @S-REG-11.1
  Scenario: S-REG-11.1 Record migrant worker and homeless status
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-11 Record migrant worker and homeless status"
    And the front desk clerk is signed on
    And "a patient who is homeless"
    When "I record that with the type"
    Then "the homeless status multiple of IHS PATIENT (#9000001) holds a new entry dated today with the status and type, and earlier answers are kept"

  @S-REG-11.2
  Scenario: S-REG-11.2 Record migrant worker and homeless status
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-11 Record migrant worker and homeless status"
    And the front desk clerk is signed on
    And "a patient who is a migrant worker"
    When "I record that with the type"
    Then "the migrant worker multiple of IHS PATIENT (#9000001) holds a new entry dated today with the status and type"

  @S-REG-11.3
  Scenario: S-REG-11.3 Record migrant worker and homeless status
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-11 Record migrant worker and homeless status"
    And the front desk clerk is signed on
    And "a status of homeless or migrant worker"
    When "I save without the type"
    Then "it is refused and asks for the type"

  @S-REG-11.4
  Scenario: S-REG-11.4 Record migrant worker and homeless status
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-11 Record migrant worker and homeless status"
    And the front desk clerk is signed on
    And "a status of not homeless"
    When "I save with a type"
    Then "the entry is filed without a type"

  @S-REG-12.1
  Scenario: S-REG-12.1 Record the patient's preferred and other names
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-12 Record the patient's preferred and other names"
    And the front desk clerk is signed on
    And "a patient"
    When "I record a preferred name"
    Then "IHS PATIENT (#9000001) holds it and the patient is listed with it beside their legal name"

  @S-REG-12.2
  Scenario: S-REG-12.2 Record the patient's preferred and other names
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-12 Record the patient's preferred and other names"
    And the front desk clerk is signed on
    And "a patient who has used other names"
    When "I add each one"
    Then "the OTHER NAME multiple (#2.01) of PATIENT (#2) holds each of them and a search by one of them lists the patient"

  @S-REG-12.3
  Scenario: S-REG-12.3 Record the patient's preferred and other names
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-12 Record the patient's preferred and other names"
    And the front desk clerk is signed on
    And "an other name that is not `LAST,FIRST MIDDLE`, or shorter than 3 or longer than 30 characters"
    When "I save"
    Then "it is refused and names the format"

  @S-REG-12.4
  Scenario: S-REG-12.4 Record the patient's preferred and other names
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-12 Record the patient's preferred and other names"
    And the front desk clerk is signed on
    And "an other name entered in error"
    When "I remove it"
    Then "the OTHER NAME multiple (#2.01) no longer holds it and the others are unchanged"

  @S-REG-13.1
  Scenario: S-REG-13.1 Record legal sex, gender identity, sexual orientation and pronouns
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-13 Record legal sex, gender identity, sexual orientation and pronouns"
    And the front desk clerk is signed on
    And "a patient"
    When "I record a legal sex with its effective date and the document that is the source"
    Then "the legal sex multiple of IHS PATIENT (#9000001) holds that entry with the date it was entered, and an earlier entry with another effective date is kept"

  @S-REG-13.2
  Scenario: S-REG-13.2 Record legal sex, gender identity, sexual orientation and pronouns
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-13 Record legal sex, gender identity, sexual orientation and pronouns"
    And the front desk clerk is signed on
    And "two legal sex entries with the same effective date"
    When "I save"
    Then "it is refused"

  @S-REG-13.3
  Scenario: S-REG-13.3 Record legal sex, gender identity, sexual orientation and pronouns
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-13 Record legal sex, gender identity, sexual orientation and pronouns"
    And the front desk clerk is signed on
    And "a patient"
    When "I record one or more gender identities and sexual orientations"
    Then "the gender identity and sexual orientation multiples of IHS PATIENT (#9000001) each hold today's entry with every choice, and an entry from an earlier date is kept"

  @S-REG-13.4
  Scenario: S-REG-13.4 Record legal sex, gender identity, sexual orientation and pronouns
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-13 Record legal sex, gender identity, sexual orientation and pronouns"
    And the front desk clerk is signed on
    And "a gender identity, sexual orientation or pronoun of other"
    When "I save without saying what"
    Then "it is refused"

  @S-REG-13.5
  Scenario: S-REG-13.5 Record legal sex, gender identity, sexual orientation and pronouns
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-13 Record legal sex, gender identity, sexual orientation and pronouns"
    And the front desk clerk is signed on
    And "a patient"
    When "I record their pronouns"
    Then "IHS PATIENT (#9000001) holds the pronouns and, for other, the text"

  @S-REG-14.1
  Scenario: S-REG-14.1 Record veteran status
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-14 Record veteran status"
    And the front desk clerk is signed on
    And "a veteran"
    When "I record the branch, entry and separation dates, service-connected status, Vietnam service and claim number"
    Then "PATIENT (#2) holds those values and IHS PATIENT (#9000001) holds today as the date the veteran information was edited"

  @S-REG-14.2
  Scenario: S-REG-14.2 Record veteran status
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-14 Record veteran status"
    And the front desk clerk is signed on
    And "a veteran with a valid VA card"
    When "I record the date a copy was obtained"
    Then "IHS PATIENT (#9000001) holds the card as valid with that date; and given no valid card, it holds whether they were told how to obtain one and no copy date"

  @S-REG-14.3
  Scenario: S-REG-14.3 Record veteran status
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-14 Record veteran status"
    And the front desk clerk is signed on
    And "a service entry date after the separation date, or either date in the future or before 1871"
    When "I save"
    Then "it is refused"

  @S-REG-14.4
  Scenario: S-REG-14.4 Record veteran status
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-14 Record veteran status"
    And the front desk clerk is signed on
    And "a claim number that is not 7 or 8 digits"
    When "I save"
    Then "it is refused and names the format"

  @S-REG-15.1
  Scenario: S-REG-15.1 Record the papers the patient signs or receives at the window
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-15 Record the papers the patient signs or receives at the window"
    And the front desk clerk is signed on
    And "a patient"
    When "I record that they received the notice of privacy practices on a date and signed the acknowledgement"
    Then "NOTICE OF PRIVACY PRACTICES (#9000038) holds the patient with those answers, me and today's date"

  @S-REG-15.2
  Scenario: S-REG-15.2 Record the papers the patient signs or receives at the window
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-15 Record the papers the patient signs or receives at the window"
    And the front desk clerk is signed on
    And "a patient who received the notice but did not sign"
    When "I save without a reason"
    Then "it is refused and asks for the reason; and given they did not receive it, no acknowledgement or reason is kept"

  @S-REG-15.3
  Scenario: S-REG-15.3 Record the papers the patient signs or receives at the window
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-15 Record the papers the patient signs or receives at the window"
    And the front desk clerk is signed on
    And "a patient"
    When "I record the date benefits were assigned"
    Then "the ASSIGN BENEFITS OBTAINED DATE multiple (#9000001.71) of IHS PATIENT (#9000001) holds a new entry for that date, and a second entry for the same date is not added"

  @S-REG-15.4
  Scenario: S-REG-15.4 Record the papers the patient signs or receives at the window
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-15 Record the papers the patient signs or receives at the window"
    And the front desk clerk is signed on
    And "a patient"
    When "I record the date they signed the release of information"
    Then "the RELEASE OF INFORMATION multiple (#9000001.03601) of IHS PATIENT (#9000001) holds an entry for that date"

  @S-REG-15.5
  Scenario: S-REG-15.5 Record the papers the patient signs or receives at the window
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-15 Record the papers the patient signs or receives at the window"
    And the front desk clerk is signed on
    And "an assignment or release date in the future"
    When "I save"
    Then "it is refused"

  @S-REG-15.6
  Scenario: S-REG-15.6 Record the papers the patient signs or receives at the window
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-15 Record the papers the patient signs or receives at the window"
    And the front desk clerk is signed on
    And "this facility's REGISTRATION PARAMETERS (#9009061) make the release of information or the assignment of benefits mandatory"
    When "I save without one"
    Then "it is refused and names it"

  @S-REG-15.7
  Scenario: S-REG-15.7 Record the papers the patient signs or receives at the window
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-15 Record the papers the patient signs or receives at the window"
    And the front desk clerk is signed on
    And "a patient"
    When "I record whether they were granted access to their personal health record on a date, and the date they were given the handout"
    Then "the PHR access and PHR handout multiples of IHS PATIENT (#9000001) hold those entries, and a second entry for the same date is refused"

  @S-REG-16.1
  Scenario: S-REG-16.1 Record consent to share records with other providers
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-16 Record consent to share records with other providers"
    And the front desk clerk is signed on
    And "an adult patient"
    When "I record their consent or refusal with the effective date and an expiration date"
    Then "the sharing consent multiple of IHS PATIENT (#9000001) holds a new entry with those dates and this facility, and earlier entries are kept unchanged"

  @S-REG-16.2
  Scenario: S-REG-16.2 Record consent to share records with other providers
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-16 Record consent to share records with other providers"
    And the front desk clerk is signed on
    And "an effective date in the future, more than five years ago, or before the patient's date of birth"
    When "I save"
    Then "it is refused"

  @S-REG-16.3
  Scenario: S-REG-16.3 Record consent to share records with other providers
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-16 Record consent to share records with other providers"
    And the front desk clerk is signed on
    And "an expiration date on or before the effective date"
    When "I save"
    Then "it is refused"

  @S-REG-16.4
  Scenario: S-REG-16.4 Record consent to share records with other providers
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-16 Record consent to share records with other providers"
    And the front desk clerk is signed on
    And "a patient under 18"
    When "I open their registration"
    Then "no sharing consent can be recorded for them and none is counted as missing"

  @S-REG-17.1
  Scenario: S-REG-17.1 Record advance directives
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-17 Record advance directives"
    And the front desk clerk is signed on
    And "a patient with a living will"
    When "I record the directive with its type and date of entry"
    Then "ADVANCE DIRECTIVE (#9000040) holds the patient and its date-of-entry multiple holds the directive with that type and date"

  @S-REG-17.2
  Scenario: S-REG-17.2 Record advance directives
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-17 Record advance directives"
    And the front desk clerk is signed on
    And "a patient with no directive"
    When "I record that with the reason"
    Then "the date-of-entry multiple of ADVANCE DIRECTIVE (#9000040) holds the answer with the reason"

  @S-REG-17.3
  Scenario: S-REG-17.3 Record advance directives
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-17 Record advance directives"
    And the front desk clerk is signed on
    And "a directive of the same type already on file for that date"
    When "I save"
    Then "it is refused"

  @S-REG-17.4
  Scenario: S-REG-17.4 Record advance directives
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-17 Record advance directives"
    And the front desk clerk is signed on
    And "a directive with no type, or no directive with no reason, or no date of entry"
    When "I save"
    Then "it is refused and names the value"

  @S-REG-17.5
  Scenario: S-REG-17.5 Record advance directives
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-17 Record advance directives"
    And the front desk clerk is signed on
    And "a directive entered in error"
    When "I remove it"
    Then "the date-of-entry multiple of ADVANCE DIRECTIVE (#9000040) no longer holds it"

  @S-REG-18.1
  Scenario: S-REG-18.1 Record legal documents on file
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-18 Record legal documents on file"
    And the front desk clerk is signed on
    And "a patient"
    When "I record a legal document with its type, document number, the date it was added to the file and its effective and end dates"
    Then "PATIENT'S LEGAL DOCS (#9000034) holds it for the patient with me and today as the entry"

  @S-REG-18.2
  Scenario: S-REG-18.2 Record legal documents on file
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-18 Record legal documents on file"
    And the front desk clerk is signed on
    And "no document type or no date added to file"
    When "I save"
    Then "it is refused and names the value"

  @S-REG-18.3
  Scenario: S-REG-18.3 Record legal documents on file
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-18 Record legal documents on file"
    And the front desk clerk is signed on
    And "an end date before the effective date"
    When "I save"
    Then "it is refused"

  @S-REG-18.4
  Scenario: S-REG-18.4 Record legal documents on file
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-18 Record legal documents on file"
    And the front desk clerk is signed on
    And "a document on file"
    When "I correct its dates, or remove it"
    Then "PATIENT'S LEGAL DOCS (#9000034) holds the corrected dates, or no longer holds it"

  @S-REG-19.1
  Scenario: S-REG-19.1 Keep notes on the registration
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-19 Keep notes on the registration"
    And the front desk clerk is signed on
    And "a patient"
    When "I write notes and save"
    Then "the notes word-processing field of IHS PATIENT (#9000001) holds the text, however long"

  @S-REG-19.2
  Scenario: S-REG-19.2 Keep notes on the registration
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-19 Keep notes on the registration"
    And the front desk clerk is signed on
    And "notes on file"
    When "I clear them and save"
    Then "IHS PATIENT (#9000001) holds no notes for the patient"

  @S-REG-20.1
  Scenario: S-REG-20.1 Keep the patient's demographics current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-20 Keep the patient's demographics current"
    And the front desk clerk is signed on
    And "a registered patient"
    When "I change their date of birth, sex, marital status, religion, place of birth, employer or employment status"
    Then "PATIENT (#2) and IHS PATIENT (#9000001) hold the new values"

  @S-REG-20.2
  Scenario: S-REG-20.2 Keep the patient's demographics current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-20 Keep the patient's demographics current"
    And the front desk clerk is signed on
    And "a registered patient"
    When "I record one or more races and ethnicities with how each was collected"
    Then "the RACE INFORMATION multiple (#2.02) and the ethnicity multiple of PATIENT (#2) hold one entry per race and ethnicity, each pointing at RACE (#10) or ETHNICITY (#10.2), with its collection method"

  @S-REG-20.3
  Scenario: S-REG-20.3 Keep the patient's demographics current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-20 Keep the patient's demographics current"
    And the front desk clerk is signed on
    And "no race or no ethnicity"
    When "I save"
    Then "it is refused and names which"

  @S-REG-20.4
  Scenario: S-REG-20.4 Keep the patient's demographics current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-20 Keep the patient's demographics current"
    And the front desk clerk is signed on
    And "the same race or ethnicity listed twice, or unknown or declined together with another"
    When "I save"
    Then "it is refused"

  @S-REG-20.5
  Scenario: S-REG-20.5 Keep the patient's demographics current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-20 Keep the patient's demographics current"
    And the front desk clerk is signed on
    And "an employer but no employment status"
    When "I save"
    Then "it is refused and asks for the status"

  @S-REG-20.6
  Scenario: S-REG-20.6 Keep the patient's demographics current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-20 Keep the patient's demographics current"
    And the front desk clerk is signed on
    And "a registered patient"
    When "I record their industries and occupations"
    Then "the industry and occupation multiple of IHS PATIENT (#9000001) holds today's entry with one line per pair, no industry twice, and each with both an industry and an occupation"

  @S-REG-20.7
  Scenario: S-REG-20.7 Keep the patient's demographics current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-20 Keep the patient's demographics current"
    And the front desk clerk is signed on
    And "a social security number already on another patient"
    When "I change the patient's number to it"
    Then "it is refused and nothing is filed"

  @S-REG-20.8
  Scenario: S-REG-20.8 Keep the patient's demographics current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-20 Keep the patient's demographics current"
    And the front desk clerk is signed on
    And "I do not hold the key that shows social security numbers (AGZVIEWSSN)"
    When "I open the patient"
    Then "the number is not shown to me"

  @S-REG-20.9
  Scenario: S-REG-20.9 Keep the patient's demographics current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-20 Keep the patient's demographics current"
    And the front desk clerk is signed on
    And "I hold only the view-only key (AGZVIEWONLY)"
    When "I open a patient"
    Then "I can see the registration and change nothing"

  @S-REG-21.1
  Scenario: S-REG-21.1 Keep the address, phones and email current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-21 Keep the address, phones and email current"
    And the front desk clerk is signed on
    And "a patient with an address on file"
    When "I change the street address, city, state, zip code or home phone, with the date they moved"
    Then "PATIENT (#2) holds the new address and the PREVIOUS MAIL ADDRESSES multiple (#9000001.83) of IHS PATIENT (#9000001) holds the old one, ended on the date they moved"

  @S-REG-21.2
  Scenario: S-REG-21.2 Keep the address, phones and email current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-21 Keep the address, phones and email current"
    And the front desk clerk is signed on
    And "a street address typed with abbreviations, or a post office box or rural route in any of its common forms"
    When "I save"
    Then "I am shown the postal standard form and PATIENT (#2) holds the address in that form"

  @S-REG-21.3
  Scenario: S-REG-21.3 Keep the address, phones and email current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-21 Keep the address, phones and email current"
    And the front desk clerk is signed on
    And "this facility's REGISTRATION PARAMETERS (#9009061) make the street address, city, state or zip code mandatory"
    When "I save without one"
    Then "it is refused and names the field"

  @S-REG-21.4
  Scenario: S-REG-21.4 Keep the address, phones and email current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-21 Keep the address, phones and email current"
    And the front desk clerk is signed on
    And "a zip code that is not 1 to 10 letters and digits, or a phone shorter than 4 digits"
    When "I save"
    Then "it is refused and names the format"

  @S-REG-21.5
  Scenario: S-REG-21.5 Keep the address, phones and email current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-21 Keep the address, phones and email current"
    And the front desk clerk is signed on
    And "a patient"
    When "I change their cell phone, work phone, other phone, email, reminder preference or pharmacy residence"
    Then "PATIENT (#2) holds the phones and IHS PATIENT (#9000001) holds the rest, and the PREVIOUS EMAIL ADDRESSES multiple (#9000001.82) holds the email that was replaced"

  @S-REG-21.6
  Scenario: S-REG-21.6 Keep the address, phones and email current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-21 Keep the address, phones and email current"
    And the front desk clerk is signed on
    And "an email address that is not in email form"
    When "I save"
    Then "it is refused"

  @S-REG-21.7
  Scenario: S-REG-21.7 Keep the address, phones and email current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-21 Keep the address, phones and email current"
    And the front desk clerk is signed on
    And "a date lived from that is in the future, before 1871 or before the patient's date of birth"
    When "I save"
    Then "it is refused"

  @S-REG-22.1
  Scenario: S-REG-22.1 Record the community, directions to the home, internet access and the address history
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-22 Record the community, directions to the home, internet access and the address history"
    And the front desk clerk is signed on
    And "a patient who has moved to another community"
    When "I record the community and the date moved"
    Then "the PREVIOUS COMMUNITY multiple (#9000001.51) of IHS PATIENT (#9000001) holds the community under that date, and IHS PATIENT (#9000001) holds it as the current community when the date is on or after the current one"

  @S-REG-22.2
  Scenario: S-REG-22.2 Record the community, directions to the home, internet access and the address history
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-22 Record the community, directions to the home, internet access and the address history"
    And the front desk clerk is signed on
    And "a community that was inactive on the date moved"
    When "I save"
    Then "it is refused"

  @S-REG-22.3
  Scenario: S-REG-22.3 Record the community, directions to the home, internet access and the address history
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-22 Record the community, directions to the home, internet access and the address history"
    And the front desk clerk is signed on
    And "a date moved in the future, before 1871, or before the patient's date of birth, or no community or date"
    When "I save"
    Then "it is refused and names the value"

  @S-REG-22.4
  Scenario: S-REG-22.4 Record the community, directions to the home, internet access and the address history
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-22 Record the community, directions to the home, internet access and the address history"
    And the front desk clerk is signed on
    And "a patient whose home is hard to find"
    When "I write directions and save"
    Then "the location-of-home word-processing field of IHS PATIENT (#9000001) holds them; and when I clear them, it holds none"

  @S-REG-22.5
  Scenario: S-REG-22.5 Record the community, directions to the home, internet access and the address history
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-22 Record the community, directions to the home, internet access and the address history"
    And the front desk clerk is signed on
    And "a patient"
    When "I record that they can use the internet and from where"
    Then "the internet access multiple of IHS PATIENT (#9000001) holds today's answer with each place, and earlier answers are kept"

  @S-REG-22.6
  Scenario: S-REG-22.6 Record the community, directions to the home, internet access and the address history
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-22 Record the community, directions to the home, internet access and the address history"
    And the front desk clerk is signed on
    And "an answer that they can use the internet"
    When "I save without saying from where"
    Then "it is refused"

  @S-REG-22.7
  Scenario: S-REG-22.7 Record the community, directions to the home, internet access and the address history
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-22 Record the community, directions to the home, internet access and the address history"
    And the front desk clerk is signed on
    And "a previous address on file"
    When "I correct its lines or the dates it was lived at"
    Then "the PREVIOUS MAIL ADDRESSES multiple (#9000001.83) holds the corrected entry"

  @S-REG-22.8
  Scenario: S-REG-22.8 Record the community, directions to the home, internet access and the address history
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-22 Record the community, directions to the home, internet access and the address history"
    And the front desk clerk is signed on
    And "a date lived to before the date lived from, or either date in the future or before 1871"
    When "I save a previous address"
    Then "it is refused"

  @S-REG-23.1
  Scenario: S-REG-23.1 See what is missing or wrong on a patient's registration
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-23 See what is missing or wrong on a patient's registration"
    And the front desk clerk is signed on
    And "a patient with no privacy notice on file, an address older than the facility allows, or coverage that has lapsed"
    When "I open their registration"
    Then "each error and warning is listed against the section it belongs to, with errors counted apart from warnings"

  @S-REG-23.2
  Scenario: S-REG-23.2 See what is missing or wrong on a patient's registration
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-23 See what is missing or wrong on a patient's registration"
    And the front desk clerk is signed on
    And "an error listed for a missing item"
    When "I record the item"
    Then "the error is no longer listed"

  @S-REG-23.3
  Scenario: S-REG-23.3 See what is missing or wrong on a patient's registration
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-23 See what is missing or wrong on a patient's registration"
    And the front desk clerk is signed on
    And "a patient under 18"
    When "I open their registration"
    Then "a missing sharing consent is not listed against them"

  @S-REG-24.1
  Scenario: S-REG-24.1 See every document on file and print the face sheet
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-24 See every document on file and print the face sheet"
    And the front desk clerk is signed on
    And "a patient with a privacy notice, assignment of benefits, release of information, advance directive, legal document, sharing consent, personal health record access, name change and restricted health information on file"
    When "I open their documents"
    Then "each is listed with its date, drawn from NOTICE OF PRIVACY PRACTICES (#9000038), the ASSIGN BENEFITS OBTAINED DATE (#9000001.71) and RELEASE OF INFORMATION (#9000001.03601) multiples, ADVANCE DIRECTIVE (#9000040), PATIENT'S LEGAL DOCS (#9000034), PATIENT NAME CHANGES (#9000033) and RESTRICTED HEALTH INFORMATION (#9000039)"

  @S-REG-24.2
  Scenario: S-REG-24.2 See every document on file and print the face sheet
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-24 See every document on file and print the face sheet"
    And the front desk clerk is signed on
    And "a patient"
    When "I print their face sheet, index card or wrist band"
    Then "the printout carries the registration as filed in PATIENT (#2) and IHS PATIENT (#9000001) on that day, and nothing is stored"

  @S-REG-25.1
  Scenario: S-REG-25.1 Change or retire a chart number
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-25 Change or retire a chart number"
    And the registration supervisor is signed on
    And "a patient with a chart at this facility"
    When "I change the number"
    Then "the HEALTH RECORD NO. multiple (#9000001.41) of IHS PATIENT (#9000001) holds the new number under this facility"

  @S-REG-25.2
  Scenario: S-REG-25.2 Change or retire a chart number
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-25 Change or retire a chart number"
    And the registration supervisor is signed on
    And "a number already assigned to another patient at this facility, or not 1 to 6 characters in the chart-number format"
    When "I save"
    Then "it is refused and names the number"

  @S-REG-25.3
  Scenario: S-REG-25.3 Change or retire a chart number
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-25 Change or retire a chart number"
    And the registration supervisor is signed on
    And "a chart registered in error, sent to archives or inactive"
    When "I set that disposition with the date"
    Then "the HEALTH RECORD NO. multiple (#9000001.41) holds the disposition, a status of inactivated and that date, the patient is listed with that status, and their registration can no longer be edited at this facility"

  @S-REG-25.4
  Scenario: S-REG-25.4 Change or retire a chart number
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-25 Change or retire a chart number"
    And the registration supervisor is signed on
    And "an inactivated chart"
    When "I set the disposition to reactivated or new chart"
    Then "the HEALTH RECORD NO. multiple (#9000001.41) holds the disposition with no status and no inactivation date, and the registration can be edited again"

  @S-REG-25.5
  Scenario: S-REG-25.5 Change or retire a chart number
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-25 Change or retire a chart number"
    And the registration supervisor is signed on
    And "I do not hold the registration manager key (AGZMGR)"
    When "I open a patient"
    Then "I cannot change their chart number or disposition"

  @S-REG-26.1
  Scenario: S-REG-26.1 Change a patient's legal name
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-26 Change a patient's legal name"
    And the registration supervisor is signed on
    And "a patient with proof of a new name"
    When "I record the new name, the proof provided and the document number"
    Then "PATIENT (#2) holds the new name, PATIENT NAME CHANGES (#9000033) holds the change with the date, proof and document, and the OTHER NAME multiple (#2.01) holds the former name"

  @S-REG-26.2
  Scenario: S-REG-26.2 Change a patient's legal name
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-26 Change a patient's legal name"
    And the registration supervisor is signed on
    And "no proof provided, or a name that is not `LAST,FIRST MIDDLE` or outside 3 to 30 characters"
    When "I save"
    Then "it is refused and names the value"

  @S-REG-26.3
  Scenario: S-REG-26.3 Change a patient's legal name
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-26 Change a patient's legal name"
    And the registration supervisor is signed on
    And "a name change on file"
    When "I correct its proof or document number"
    Then "PATIENT NAME CHANGES (#9000033) holds the correction and the patient's name is unchanged"

  @S-REG-26.4
  Scenario: S-REG-26.4 Change a patient's legal name
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-26 Change a patient's legal name"
    And the registration supervisor is signed on
    And "I do not hold the registration manager key (AGZMGR)"
    When "I open a patient"
    Then "I cannot change their legal name"

  @S-REG-27.1
  Scenario: S-REG-27.1 Record a patient's death
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-27 Record a patient's death"
    And the registration supervisor is signed on
    And "a living patient"
    When "I record the date and time of death, the state, the certificate number and the preliminary cause"
    Then "PATIENT (#2) holds the date of death and me as the user who entered it, IHS PATIENT (#9000001) holds the state, certificate number and the date edited, and the patient is listed as deceased"

  @S-REG-27.2
  Scenario: S-REG-27.2 Record a patient's death
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-27 Record a patient's death"
    And the registration supervisor is signed on
    And "a date of death before the patient's date of birth, or in the future"
    When "I save"
    Then "it is refused"

  @S-REG-27.3
  Scenario: S-REG-27.3 Record a patient's death
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-27 Record a patient's death"
    And the registration supervisor is signed on
    And "a death on file"
    When "any user opens the patient"
    Then "the registration can be seen and nothing in it changed"

  @S-REG-27.4
  Scenario: S-REG-27.4 Record a patient's death
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-27 Record a patient's death"
    And the registration supervisor is signed on
    And "a death entered in error"
    When "I clear it"
    Then "PATIENT (#2) holds no date of death and the registration can be edited again"

  @S-REG-27.5
  Scenario: S-REG-27.5 Record a patient's death
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-27 Record a patient's death"
    And the registration supervisor is signed on
    And "I do not hold the registration manager key (AGZMGR)"
    When "I open a patient"
    Then "I cannot record or clear a death"

  @S-REG-28.1
  Scenario: S-REG-28.1 Assign and work a patient record flag
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-28 Assign and work a patient record flag"
    And the him technician is signed on
    And "a patient and a flag from PRF NATIONAL FLAG (#26.15) or PRF LOCAL FLAG (#26.11)"
    When "I assign it with the owner site, the narrative, who approved it and the review date"
    Then "PRF ASSIGNMENT (#26.13) holds an active assignment for the patient with those values and the narrative, PRF ASSIGNMENT HISTORY (#26.14) holds a new-assignment action entered by me and approved by that person, and the patient is listed as flagged"

  @S-REG-28.2
  Scenario: S-REG-28.2 Assign and work a patient record flag
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-28 Assign and work a patient record flag"
    And the him technician is signed on
    And "a flag already assigned to the patient"
    When "I assign the same flag again"
    Then "it is refused"

  @S-REG-28.3
  Scenario: S-REG-28.3 Assign and work a patient record flag
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-28 Assign and work a patient record flag"
    And the him technician is signed on
    And "a flag with a review frequency"
    When "I save with a review date before today, after today plus the frequency, or none"
    Then "it is refused and names the date"

  @S-REG-28.4
  Scenario: S-REG-28.4 Assign and work a patient record flag
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-28 Assign and work a patient record flag"
    And the him technician is signed on
    And "no owner site, narrative, approver or flag"
    When "I save"
    Then "it is refused and names the value"

  @S-REG-28.5
  Scenario: S-REG-28.5 Assign and work a patient record flag
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-28 Assign and work a patient record flag"
    And the him technician is signed on
    And "an active assignment"
    When "I continue or reactivate it with a reason, an approver and a new review date"
    Then "PRF ASSIGNMENT (#26.13) holds the new review date and an active status, and PRF ASSIGNMENT HISTORY (#26.14) holds that action with the reason"

  @S-REG-28.6
  Scenario: S-REG-28.6 Assign and work a patient record flag
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-28 Assign and work a patient record flag"
    And the him technician is signed on
    And "an active assignment"
    When "I inactivate it, or mark it entered in error, with a reason and an approver"
    Then "PRF ASSIGNMENT (#26.13) holds an inactive status and PRF ASSIGNMENT HISTORY (#26.14) holds that action with the reason, and the patient is no longer listed as flagged for it"

  @S-REG-28.7
  Scenario: S-REG-28.7 Assign and work a patient record flag
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-28 Assign and work a patient record flag"
    And the him technician is signed on
    And "I do not hold the flag assignment key (DGPF ASSIGNMENT)"
    When "I open a patient"
    Then "I cannot assign a new flag"

  @S-REG-29.1
  Scenario: S-REG-29.1 Track a request to restrict health information
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-29 Track a request to restrict health information"
    And the him technician is signed on
    And "a patient who asks for a restriction"
    When "I record it as pending with the date and the reason"
    Then "RESTRICTED HEALTH INFORMATION (#9000039) holds the patient with that status, reason and date, entered by me today, and the patient is listed as restricted"

  @S-REG-29.2
  Scenario: S-REG-29.2 Track a request to restrict health information
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-29 Track a request to restrict health information"
    And the him technician is signed on
    And "a pending request"
    When "I record it as approved with the date and the approving official"
    Then "RESTRICTED HEALTH INFORMATION (#9000039) holds the approval with that official and date, by me today"

  @S-REG-29.3
  Scenario: S-REG-29.3 Track a request to restrict health information
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-29 Track a request to restrict health information"
    And the him technician is signed on
    And "a request"
    When "I record it as not approved, or revoked, with the date and the official"
    Then "RESTRICTED HEALTH INFORMATION (#9000039) holds that status with the official and date"

  @S-REG-29.4
  Scenario: S-REG-29.4 Track a request to restrict health information
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-29 Track a request to restrict health information"
    And the him technician is signed on
    And "a status that needs a date or an official"
    When "I save without them, or with an official's name outside 3 to 20 characters, or with no reason"
    Then "it is refused and names the value"

  @S-REG-29.5
  Scenario: S-REG-29.5 Track a request to restrict health information
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-29 Track a request to restrict health information"
    And the him technician is signed on
    And "a request entered in error"
    When "I mark it so"
    Then "RESTRICTED HEALTH INFORMATION (#9000039) holds that status with me and today, and the patient is no longer listed as restricted"

  @S-REG-30.1
  Scenario: S-REG-30.1 Run registration reports
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-30 Run registration reports"
    And the registration supervisor is signed on
    And "patients added and edited over a date range"
    When "I run the daily activity report for those dates"
    Then "it lists the patients by the date of their last registration update in IHS PATIENT (#9000001), or the counts of new, edited and removed, as I chose"

  @S-REG-30.2
  Scenario: S-REG-30.2 Run registration reports
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-30 Run registration reports"
    And the registration supervisor is signed on
    And "patients registered quickly with a generated chart number"
    When "I run the temporary charts report"
    Then "it lists each patient whose number in the HEALTH RECORD NO. multiple (#9000001.41) at this facility is temporary"

  @S-REG-30.3
  Scenario: S-REG-30.3 Run registration reports
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-30 Run registration reports"
    And the registration supervisor is signed on
    And "patients with coverage on file"
    When "I run the insurance coverage or enrollment report for a resource, age range and eligibility status"
    Then "it lists the patients whose coverage matches"

  @S-REG-30.4
  Scenario: S-REG-30.4 Run registration reports
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-REG-30 Run registration reports"
    And the registration supervisor is signed on
    And "I hold none of the keys that allow the reports (AGZMGR, AGZMENU, AGZVIEWONLY)"
    When "I open registration"
    Then "I cannot run them. ## W02 Scheduling Drafts from BPRM 4.0 p6's Scheduling module (lakeraven-ehr#565): what a scheduler and the front desk can do to an appointment, the rules BPRM enforces, and the wait list, letters and reports around it. An appointment is filed where IHS scheduling files it, on the clinic in HOSPITAL LOCATION (#44) and on the patient in PATIENT (#2.98); whether BSDX APPOINTMENT (#9002018.4) is written too is the parity question in lakeraven-ehr's `docs/BPRM_PARITY_PLAN.md`, so the stories assert the two files every interface shares. Clinics, access types, holidays, resource groups and which users may work which clinic are left to a site-setup workflow"
