# GENERATED by bin/bprm_stubs from docs/bprm/scenarios.tsv (rpms-ux 7f076114c7126241b12c06f790a10bc93ea70442). Do not edit.
# A scenario leaves this file by being written, with the same tag, in
# features/bprm_twin/w02_*/ and rerunning bin/bprm_stubs.
@bprm_twin @bprm_stub @W02
Feature: W02 Scheduling: scenarios no lakeraven-ehr screen drives yet

  @S-SCH-01.2
  Scenario: S-SCH-01.2 Book an appointment
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-01 Book an appointment"
    And the scheduler is signed on
    And "a slot that is full"
    When "I try to book it"
    Then "I am told it is full, or asked to overbook if I hold the key for it"

  @S-SCH-01.5
  Scenario: S-SCH-01.5 Book an appointment
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-01 Book an appointment"
    And the scheduler is signed on
    And "the patient already has an active appointment (not cancelled, not a no-show) at that date and time in PATIENT (#2.98)"
    When "I book"
    Then "it is refused and the existing appointment is unchanged"

  @S-SCH-01.6
  Scenario: S-SCH-01.6 Book an appointment
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-01 Book an appointment"
    And the scheduler is signed on
    And "a patient with a date of death in PATIENT (#2)"
    When "I book"
    Then "it is refused"

  @S-SCH-01.7
  Scenario: S-SCH-01.7 Book an appointment
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-01 Book an appointment"
    And the scheduler is signed on
    And "a clinic whose inactivate date in HOSPITAL LOCATION (#44) is on or before the chosen date and whose reactivate date is absent or later"
    When "I book"
    Then "it is refused and nothing is filed"

  @S-SCH-01.8
  Scenario: S-SCH-01.8 Book an appointment
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-01 Book an appointment"
    And the scheduler is signed on
    And "a date further ahead than the clinic's maximum days for future booking in HOSPITAL LOCATION (#44)"
    When "I book"
    Then "it is refused"

  @S-SCH-01.9
  Scenario: S-SCH-01.9 Book an appointment
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-01 Book an appointment"
    And the scheduler is signed on
    And "a time with no access block for the clinic's resource in BSDX ACCESS BLOCK (#9002018.3), or one whose access type in BSDX ACCESS TYPE (#9002018.35) prevents access"
    When "I book without the master overbook right on that resource in BSDX RESOURCE USER (#9002018.15) and without SDZSUP"
    Then "it is refused; with either, I am asked to confirm and the appointment is filed as an overbook"

  @S-SCH-01.10
  Scenario: S-SCH-01.10 Book an appointment
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-01 Book an appointment"
    And the scheduler is signed on
    And "a slot whose active appointments already equal the block's slot count, the overbook right on that resource for me in BSDX RESOURCE USER (#9002018.15), and fewer overbooks today on the clinic than its maximum per day in HOSPITAL LOCATION (#44)"
    When "I confirm the overbook"
    Then "the appointment is on the clinic in HOSPITAL LOCATION (#44.003) and on the patient in PATIENT (#2.98), marked as an overbook"

  @S-SCH-01.11
  Scenario: S-SCH-01.11 Book an appointment
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-01 Book an appointment"
    And the scheduler is signed on
    And "a full slot and the clinic's overbooks for that day already at its maximum, and I hold neither the master overbook right on the resource nor SDZSUP"
    When "I try to book"
    Then "it is refused and no appointment is filed"

  @S-SCH-01.12
  Scenario: S-SCH-01.12 Book an appointment
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-01 Book an appointment"
    And the scheduler is signed on
    And "I hold neither SDZSUP nor SDZMENU"
    When "I open scheduling"
    Then "I cannot see a clinic's schedule or book, cancel, check in, check out or run a scheduling report"

  @S-SCH-01.13
  Scenario: S-SCH-01.13 Book an appointment
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-01 Book an appointment"
    And the scheduler is signed on
    And "a clinic whose resource gives my user no right to modify appointments in BSDX RESOURCE USER (#9002018.15), or a clinic marked as prohibiting access in HOSPITAL LOCATION (#44), and I do not hold SDZSUP"
    When "I open its schedule"
    Then "I can see it but cannot book, cancel, check in or out, or mark a no-show on it"

  @S-SCH-02.1
  Scenario: S-SCH-02.1 Cancel or reschedule
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-02 Cancel or reschedule"
    And the scheduler is signed on
    And "a booked appointment"
    When "I cancel it with a reason"
    Then "the slot is open again and the appointment is marked cancelled by patient or clinic, with the reason"

  @S-SCH-02.2
  Scenario: S-SCH-02.2 Cancel or reschedule
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-02 Cancel or reschedule"
    And the scheduler is signed on
    And "a booked appointment"
    When "I cancel it without saying whether the patient or the clinic cancelled, or without a reason"
    Then "it is refused and the appointment stays booked"

  @S-SCH-02.3
  Scenario: S-SCH-02.3 Cancel or reschedule
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-02 Cancel or reschedule"
    And the scheduler is signed on
    And "cancellation remarks shorter than 3 or longer than 160 characters"
    When "I save"
    Then "it is refused"

  @S-SCH-02.4
  Scenario: S-SCH-02.4 Cancel or reschedule
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-02 Cancel or reschedule"
    And the scheduler is signed on
    And "reasons in CANCELLATION REASONS (#409.2) typed for the clinic, for the patient or for both"
    When "I cancel on the clinic's behalf"
    Then "only a reason typed clinic or both can be filed, and likewise patient or both when the patient cancelled"

  @S-SCH-02.5
  Scenario: S-SCH-02.5 Cancel or reschedule
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-02 Cancel or reschedule"
    And the scheduler is signed on
    And "an appointment the patient has already been checked in for"
    When "I cancel it"
    Then "it is refused; the check-in has to be undone first"

  @S-SCH-02.6
  Scenario: S-SCH-02.6 Cancel or reschedule
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-02 Cancel or reschedule"
    And the scheduler is signed on
    And "an appointment already cancelled or marked no-show"
    When "I cancel it"
    Then "it is refused"

  @S-SCH-02.7
  Scenario: S-SCH-02.7 Cancel or reschedule
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-02 Cancel or reschedule"
    And the scheduler is signed on
    And "a booked appointment"
    When "I cancel it on the clinic's behalf with a reason and remarks"
    Then "PATIENT (#2.98) holds the status cancelled by clinic, who cancelled it, when, the reason and the remarks, and the entry on the clinic in HOSPITAL LOCATION (#44.003) is gone so the slot counts as free"

  @S-SCH-02.8
  Scenario: S-SCH-02.8 Cancel or reschedule
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-02 Cancel or reschedule"
    And the scheduler is signed on
    And "a booked appointment and an open slot in the same or another of my clinics"
    When "I move it there with a cancellation type and reason"
    Then "the original is cancelled in PATIENT (#2.98) with that type and reason and a remark that it was rescheduled to the new time, and a new appointment is filed at the new time in HOSPITAL LOCATION (#44.003) and PATIENT (#2.98) carrying the original's note"

  @S-SCH-02.9
  Scenario: S-SCH-02.9 Cancel or reschedule
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-02 Cancel or reschedule"
    And the scheduler is signed on
    And "an appointment that is checked in, cancelled or a no-show"
    When "I try to move it"
    Then "it is refused"

  @S-SCH-02.10
  Scenario: S-SCH-02.10 Cancel or reschedule
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-02 Cancel or reschedule"
    And the scheduler is signed on
    And "the new slot is full or blocked"
    When "I move an appointment there"
    Then "the overbook rules of S-SCH-01 apply, and when they refuse the original stays booked"

  @S-SCH-02.11
  Scenario: S-SCH-02.11 Cancel or reschedule
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-02 Cancel or reschedule"
    And the scheduler is signed on
    And "an appointment cancelled by the patient or by the clinic"
    When "I undo the cancellation with an appointment length"
    Then "PATIENT (#2.98) no longer holds a cancellation status, reason or canceller, and the appointment is on the clinic again in HOSPITAL LOCATION (#44.003) with that length"

  @S-SCH-02.12
  Scenario: S-SCH-02.12 Cancel or reschedule
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-02 Cancel or reschedule"
    And the scheduler is signed on
    And "a cancelled appointment whose slot has since been filled"
    When "I undo the cancellation"
    Then "it is refused"

  @S-SCH-02.13
  Scenario: S-SCH-02.13 Cancel or reschedule
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-02 Cancel or reschedule"
    And the scheduler is signed on
    And "an appointment that is not cancelled"
    When "I undo a cancellation"
    Then "it is refused"

  @S-SCH-03.1
  Scenario: S-SCH-03.1 Check the patient in
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-03 Check the patient in"
    And the front desk clerk is signed on
    And "a patient with an appointment today"
    When "I check them in"
    Then "the appointment shows checked in with the time, and a visit is created for the clinic and date"

  @S-SCH-03.2
  Scenario: S-SCH-03.2 Check the patient in
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-03 Check the patient in"
    And the front desk clerk is signed on
    And "a patient with an appointment today and a clinic with a default provider"
    When "I check them in naming the provider"
    Then "HOSPITAL LOCATION (#44.003) holds the check-in time, me as the user who checked in and when it was entered, and VISIT (#9000010) holds a visit for the patient at the clinic on that date with that provider"

  @S-SCH-03.3
  Scenario: S-SCH-03.3 Check the patient in
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-03 Check the patient in"
    And the front desk clerk is signed on
    And "a check-in date that differs from the appointment's date, or lies in the future"
    When "I save"
    Then "it is refused and nothing is filed"

  @S-SCH-03.4
  Scenario: S-SCH-03.4 Check the patient in
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-03 Check the patient in"
    And the front desk clerk is signed on
    And "a clinic that requires a visit provider in CLINIC SETUP PARAMETERS (#9009017.2)"
    When "I check in without naming one"
    Then "it is refused"

  @S-SCH-03.5
  Scenario: S-SCH-03.5 Check the patient in
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-03 Check the patient in"
    And the front desk clerk is signed on
    And "a clinic set up to use several clinic stop codes in CLINIC SETUP PARAMETERS (#9009017.2)"
    When "I check in without choosing a stop from CLINIC STOP (#40.7)"
    Then "it is refused; a clinic with one stop files its own"

  @S-SCH-03.6
  Scenario: S-SCH-03.6 Check the patient in
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-03 Check the patient in"
    And the front desk clerk is signed on
    And "a patient whose health record number at this facility is a temporary one"
    When "I check them in"
    Then "it is refused"

  @S-SCH-03.7
  Scenario: S-SCH-03.7 Check the patient in
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-03 Check the patient in"
    And the front desk clerk is signed on
    And "an appointment already checked in, checked out, cancelled or marked no-show"
    When "I check it in"
    Then "it is refused"

  @S-SCH-03.8
  Scenario: S-SCH-03.8 Check the patient in
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-03 Check the patient in"
    And the front desk clerk is signed on
    And "a check-in with a routing slip asked for on a named printer"
    When "I save"
    Then "the routing slip for that patient and appointment prints to that device after the check-in is filed"

  @S-SCH-03.9
  Scenario: S-SCH-03.9 Check the patient in
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-03 Check the patient in"
    And the front desk clerk is signed on
    And "a checked-in appointment"
    When "I undo the check-in"
    Then "HOSPITAL LOCATION (#44.003) no longer holds a check-in time or user and the appointment is scheduled again"

  @S-SCH-04.1
  Scenario: S-SCH-04.1 Search for an open slot across days
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-04 Search for an open slot across days"
    And the scheduler is signed on
    And "a clinic whose resource in BSDX RESOURCE (#9002018.1) has access blocks in BSDX ACCESS BLOCK (#9002018.3) over a week"
    When "I search for slots of the clinic's appointment length between two dates"
    Then "every slot returned starts inside one of those blocks on a day in the range, no earlier than the clinic's display start hour in HOSPITAL LOCATION (#44), ends within the block, and the block has fewer active appointments (scheduled, checked in or checked out) over that time than its slot count"

  @S-SCH-04.2
  Scenario: S-SCH-04.2 Search for an open slot across days
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-04 Search for an open slot across days"
    And the scheduler is signed on
    And "an access block whose access type in BSDX ACCESS TYPE (#9002018.35) prevents access"
    When "I search"
    Then "no slot inside it is returned"

  @S-SCH-04.3
  Scenario: S-SCH-04.3 Search for an open slot across days
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-04 Search for an open slot across days"
    And the scheduler is signed on
    And "a date in HOLIDAY (#40.5) and a clinic that does not schedule on holidays in HOSPITAL LOCATION (#44)"
    When "I search across it"
    Then "no slot on that date is returned; a clinic that schedules on holidays returns its slots as usual"

  @S-SCH-04.4
  Scenario: S-SCH-04.4 Search for an open slot across days
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-04 Search for an open slot across days"
    And the scheduler is signed on
    And "dates beyond the clinic's maximum days for future booking, or inside its inactive period, in HOSPITAL LOCATION (#44)"
    When "I search"
    Then "no slot on those dates is returned"

  @S-SCH-04.5
  Scenario: S-SCH-04.5 Search for an open slot across days
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-04 Search for an open slot across days"
    And the scheduler is signed on
    And "I restrict the search to mornings or to afternoons"
    When "I search"
    Then "only slots starting before noon, or from noon, are returned"

  @S-SCH-04.6
  Scenario: S-SCH-04.6 Search for an open slot across days
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-04 Search for an open slot across days"
    And the scheduler is signed on
    And "I restrict the search to one access type"
    When "I search"
    Then "only slots in blocks of that type are returned"

  @S-SCH-04.7
  Scenario: S-SCH-04.7 Search for an open slot across days
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-04 Search for an open slot across days"
    And the scheduler is signed on
    And "a slot found by the search"
    When "I pick it and name a registered patient"
    Then "the appointment is filed as in S-SCH-01.1 at that time with the slot's length"

  @S-SCH-05.1
  Scenario: S-SCH-05.1 See the clinic's schedule and the appointment lists
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-05 See the clinic's schedule and the appointment lists"
    And the scheduler is signed on
    And "clinics whose resources name my user in BSDX RESOURCE USER (#9002018.15) at this facility"
    When "I open the schedule"
    Then "exactly those clinics are offered to me; holding SDZSUP, every clinic resource of the facility in BSDX RESOURCE (#9002018.1) is"

  @S-SCH-05.2
  Scenario: S-SCH-05.2 See the clinic's schedule and the appointment lists
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-05 See the clinic's schedule and the appointment lists"
    And the scheduler is signed on
    And "a clinic's access blocks for the week in BSDX ACCESS BLOCK (#9002018.3) and a date in HOLIDAY (#40.5)"
    When "I view a day"
    Then "each block shows with its access type and slot count, and the holiday shows as blocked for the whole day unless the clinic schedules on holidays in HOSPITAL LOCATION (#44)"

  @S-SCH-05.3
  Scenario: S-SCH-05.3 See the clinic's schedule and the appointment lists
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-05 See the clinic's schedule and the appointment lists"
    And the scheduler is signed on
    And "appointments of every status on a day"
    When "I view the day"
    Then "each shows with its status (scheduled, checked in, checked out, cancelled by clinic, cancelled by patient or no-show), and overbooks are marked"

  @S-SCH-05.4
  Scenario: S-SCH-05.4 See the clinic's schedule and the appointment lists
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-05 See the clinic's schedule and the appointment lists"
    And the scheduler is signed on
    And "another user books, cancels or checks in an appointment on a clinic I am viewing"
    When "they save"
    Then "my view shows the change without my reloading it"

  @S-SCH-05.5
  Scenario: S-SCH-05.5 See the clinic's schedule and the appointment lists
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-05 See the clinic's schedule and the appointment lists"
    And the scheduler is signed on
    And "today's appointments across several of my clinics"
    When "I list them filtered to checked in"
    Then "exactly those checked in and neither checked out nor cancelled are listed; and I can list today's, future, past or all appointments, sorted by appointment time, patient, check-in, check-out or no-show/cancel time"

  @S-SCH-05.6
  Scenario: S-SCH-05.6 See the clinic's schedule and the appointment lists
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-05 See the clinic's schedule and the appointment lists"
    And the scheduler is signed on
    And "a patient with appointments in several clinics"
    When "I open that patient's appointments"
    Then "every one is listed with its clinic and division, status, type (scheduled or walk-in), who made it and when, and its check-in, check-out and cancellation details, and I can act on those in my clinics"

  @S-SCH-06.1
  Scenario: S-SCH-06.1 Book a walk-in
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-06 Book a walk-in"
    And the front desk clerk is signed on
    And "a registered patient at the window with no appointment and a clinic I may modify appointments on"
    When "I book a walk-in at the current time naming the provider and clinic stop"
    Then "the appointment is on the clinic in HOSPITAL LOCATION (#44.003) and on the patient in PATIENT (#2.98) typed as a walk-in, checked in at that time by me, and VISIT (#9000010) holds the visit"

  @S-SCH-06.2
  Scenario: S-SCH-06.2 Book a walk-in
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-06 Book a walk-in"
    And the front desk clerk is signed on
    And "the current slot is full or blocked"
    When "I book the walk-in"
    Then "the overbook rules of S-SCH-01 apply"

  @S-SCH-06.3
  Scenario: S-SCH-06.3 Book a walk-in
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-06 Book a walk-in"
    And the front desk clerk is signed on
    And "a required check-in value missing (the provider when the clinic requires one, the stop when it uses several, the check-in time)"
    When "I save"
    Then "it is refused and neither an appointment nor a visit is filed"

  @S-SCH-06.4
  Scenario: S-SCH-06.4 Book a walk-in
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-06 Book a walk-in"
    And the front desk clerk is signed on
    And "the patient has an open entry on this clinic's wait list"
    When "I book the walk-in and ask to take them off it"
    Then "their entry in WAITING LIST (#9009017.11) is closed today with the resolution that an appointment was made"

  @S-SCH-07.1
  Scenario: S-SCH-07.1 Check the patient out
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-07 Check the patient out"
    And the front desk clerk is signed on
    And "a checked-in appointment"
    When "I check the patient out with the time"
    Then "HOSPITAL LOCATION (#44.003) holds the check-out time, me as the user who checked out and when it was entered"

  @S-SCH-07.2
  Scenario: S-SCH-07.2 Check the patient out
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-07 Check the patient out"
    And the front desk clerk is signed on
    And "an appointment that is not checked in"
    When "I check it out"
    Then "it is refused"

  @S-SCH-07.3
  Scenario: S-SCH-07.3 Check the patient out
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-07 Check the patient out"
    And the front desk clerk is signed on
    And "a check-out date before the appointment's date or in the future, or a check-out time earlier than the check-in time on the same day"
    When "I save"
    Then "it is refused and nothing is filed"

  @S-SCH-07.4
  Scenario: S-SCH-07.4 Check the patient out
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-07 Check the patient out"
    And the front desk clerk is signed on
    And "a check-out time more than five minutes ahead of the server's clock"
    When "I save"
    Then "it is refused; a time a few minutes ahead is filed as the server's current time"

  @S-SCH-07.5
  Scenario: S-SCH-07.5 Check the patient out
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-07 Check the patient out"
    And the front desk clerk is signed on
    And "a patient who needs a follow-up and no slot to give them"
    When "I check them out and add them to the clinic's wait list with a reason, priority and recall date"
    Then "WAITING LIST (#9009017.1) for the clinic holds the patient (#9009017.11) with those values, today as the date added, me as the user who added them and the clinic's default provider"

  @S-SCH-07.6
  Scenario: S-SCH-07.6 Check the patient out
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-07 Check the patient out"
    And the front desk clerk is signed on
    And "a checked-out appointment"
    When "I undo the check-out"
    Then "HOSPITAL LOCATION (#44.003) no longer holds a check-out time or user and the appointment is checked in again"

  @S-SCH-08.1
  Scenario: S-SCH-08.1 Record a no-show
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-08 Record a no-show"
    And the scheduler is signed on
    And "a scheduled appointment whose time has passed with no check-in"
    When "I mark it a no-show with remarks"
    Then "PATIENT (#2.98) holds the status no-show, me as who marked it, when, the clinic and the remarks, and the appointment no longer counts against the slot"

  @S-SCH-08.2
  Scenario: S-SCH-08.2 Record a no-show
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-08 Record a no-show"
    And the scheduler is signed on
    And "an appointment whose time has not yet passed, or one already checked in, cancelled or a no-show"
    When "I mark it a no-show"
    Then "it is refused"

  @S-SCH-08.3
  Scenario: S-SCH-08.3 Record a no-show
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-08 Record a no-show"
    And the scheduler is signed on
    And "remarks shorter than 3 or longer than 160 characters"
    When "I save"
    Then "it is refused"

  @S-SCH-08.4
  Scenario: S-SCH-08.4 Record a no-show
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-08 Record a no-show"
    And the scheduler is signed on
    And "a no-show appointment"
    When "I undo the no-show"
    Then "PATIENT (#2.98) no longer holds the no-show status and the appointment is on the clinic again in HOSPITAL LOCATION (#44.003) with its length and note"

  @S-SCH-08.5
  Scenario: S-SCH-08.5 Record a no-show
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-08 Record a no-show"
    And the scheduler is signed on
    And "a no-show appointment whose slot has since been filled"
    When "I undo the no-show"
    Then "it is refused"

  @S-SCH-09.1
  Scenario: S-SCH-09.1 Keep an appointment's details current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-09 Keep an appointment's details current"
    And the scheduler is signed on
    And "a booked appointment"
    When "I change its note"
    Then "HOSPITAL LOCATION (#44.003) holds the new note on that appointment and nothing else about it changes"

  @S-SCH-09.2
  Scenario: S-SCH-09.2 Keep an appointment's details current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-09 Keep an appointment's details current"
    And the scheduler is signed on
    And "a note shorter than 2 or longer than 150 characters, or containing a semicolon or a colon"
    When "I save"
    Then "it is refused"

  @S-SCH-09.3
  Scenario: S-SCH-09.3 Keep an appointment's details current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-09 Keep an appointment's details current"
    And the scheduler is signed on
    And "a cancelled or no-show appointment"
    When "I change its remarks to between 3 and 160 characters"
    Then "PATIENT (#2.98) holds the new remarks"

  @S-SCH-09.4
  Scenario: S-SCH-09.4 Keep an appointment's details current
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-09 Keep an appointment's details current"
    And the scheduler is signed on
    And "a booked appointment on a clinic that allows variable appointment lengths in HOSPITAL LOCATION (#44)"
    When "I change its length"
    Then "HOSPITAL LOCATION (#44.003) holds the new length and the start time is unchanged"

  @S-SCH-10.1
  Scenario: S-SCH-10.1 Keep the clinic's wait list
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-10 Keep the clinic's wait list"
    And the scheduler is signed on
    And "a patient who needs an appointment and a clinic with a wait list"
    When "I add them with the date added, a reason, a priority, a provider, a recall date and comments"
    Then "WAITING LIST (#9009017.1) for that clinic holds the patient (#9009017.11) with those values and me as the user who added them, and the reason is one typed for adding in WAITING LIST REASON (#9009017.4)"

  @S-SCH-10.2
  Scenario: S-SCH-10.2 Keep the clinic's wait list
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-10 Keep the clinic's wait list"
    And the scheduler is signed on
    And "no patient, clinic, date added, reason or recall date"
    When "I save"
    Then "it is refused and nothing is filed"

  @S-SCH-10.3
  Scenario: S-SCH-10.3 Keep the clinic's wait list
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-10 Keep the clinic's wait list"
    And the scheduler is signed on
    And "a clinic whose wait list is marked inactive in WAITING LIST (#9009017.1)"
    When "I add a patient"
    Then "that clinic cannot be chosen"

  @S-SCH-10.4
  Scenario: S-SCH-10.4 Keep the clinic's wait list
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-10 Keep the clinic's wait list"
    And the scheduler is signed on
    And "an open entry"
    When "I change its reason, priority, provider, recall date or comments"
    Then "the entry holds the new values and is still open"

  @S-SCH-10.5
  Scenario: S-SCH-10.5 Keep the clinic's wait list
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-10 Keep the clinic's wait list"
    And the scheduler is signed on
    And "an open entry"
    When "I remove it with the date removed and a resolution typed for removal in WAITING LIST REASON (#9009017.4)"
    Then "the entry holds that date, resolution and me as the user who removed it, and it is closed"

  @S-SCH-10.6
  Scenario: S-SCH-10.6 Keep the clinic's wait list
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-10 Keep the clinic's wait list"
    And the scheduler is signed on
    And "a removal without a date removed or a resolution"
    When "I save"
    Then "it is refused and the entry stays open"

  @S-SCH-10.7
  Scenario: S-SCH-10.7 Keep the clinic's wait list
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-10 Keep the clinic's wait list"
    And the scheduler is signed on
    And "an open entry"
    When "I book the patient from the wait list into a slot of that clinic"
    Then "the appointment is filed as in S-SCH-01.1 and the entry is closed today with the resolution that an appointment was made and a comment naming the clinic and time"

  @S-SCH-10.8
  Scenario: S-SCH-10.8 Keep the clinic's wait list
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-10 Keep the clinic's wait list"
    And the scheduler is signed on
    And "a closed entry"
    When "I open the wait list"
    Then "I can read and edit it but neither remove it nor book from it again"

  @S-SCH-10.9
  Scenario: S-SCH-10.9 Keep the clinic's wait list
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-10 Keep the clinic's wait list"
    And the scheduler is signed on
    And "entries across my clinics, open and closed"
    When "I list one clinic's wait list for a recall-date range, open only"
    Then "exactly the open entries of that clinic with a recall date in the range are listed, in recall-date then priority order"

  @S-SCH-11.1
  Scenario: S-SCH-11.1 Print appointment letters
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-11 Print appointment letters"
    And the scheduler is signed on
    And "a clinic whose pre-appointment letter in HOSPITAL LOCATION (#44) names a template in LETTER (#407.5), and patients with scheduled appointments in a date range"
    When "I print the clinic's pre-appointment letters for that range"
    Then "one letter per patient is produced with their name, address and health record number, the template's opening and closing text, and each of their appointments in the range with clinic and time; cancelled, no-show and checked-in appointments and deceased patients are left out"

  @S-SCH-11.2
  Scenario: S-SCH-11.2 Print appointment letters
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-11 Print appointment letters"
    And the scheduler is signed on
    And "a template that greets the parents and a patient under 18"
    When "I print"
    Then "that patient's letter is addressed to their parents"

  @S-SCH-11.3
  Scenario: S-SCH-11.3 Print appointment letters
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-11 Print appointment letters"
    And the scheduler is signed on
    And "appointments in the range cancelled by the clinic, cancelled by the patient, and marked no-show in PATIENT (#2.98)"
    When "I print letters of one of those three kinds"
    Then "only the patients with appointments of that kind get a letter, on the clinic's template of that kind"

  @S-SCH-11.4
  Scenario: S-SCH-11.4 Print appointment letters
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-11 Print appointment letters"
    And the scheduler is signed on
    And "a clinic with no template of the chosen kind in HOSPITAL LOCATION (#44) and none chosen by hand, or no appointments of that kind in the range"
    When "I print"
    Then "no letter is produced and I am told which of the two it was"

  @S-SCH-11.5
  Scenario: S-SCH-11.5 Print appointment letters
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-11 Print appointment letters"
    And the scheduler is signed on
    And "one appointment that is scheduled, cancelled or a no-show"
    When "I print its letter from the appointment"
    Then "only that patient's letter of the matching kind is produced"

  @S-SCH-12.1
  Scenario: S-SCH-12.1 Maintain a letter template
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-12 Maintain a letter template"
    And the scheduler is signed on
    And "I hold SDZSUP"
    When "I add a letter with a name of 3 to 30 characters, one of the four kinds (pre-appointment, clinic cancellation, appointment cancellation, no-show), an opening and a closing text, and whether it greets the parents"
    Then "LETTER (#407.5) holds it with those values"

  @S-SCH-12.2
  Scenario: S-SCH-12.2 Maintain a letter template
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-12 Maintain a letter template"
    And the scheduler is signed on
    And "a name missing or outside 3 to 30 characters, or no kind"
    When "I save"
    Then "it is refused and nothing is filed"

  @S-SCH-12.3
  Scenario: S-SCH-12.3 Maintain a letter template
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-12 Maintain a letter template"
    And the scheduler is signed on
    And "an existing letter"
    When "I change its name, texts or the parents greeting"
    Then "LETTER (#407.5) holds the new values and its kind is unchanged"

  @S-SCH-12.4
  Scenario: S-SCH-12.4 Maintain a letter template
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-12 Maintain a letter template"
    And the scheduler is signed on
    And "I do not hold SDZSUP"
    When "I open scheduling"
    Then "I cannot add or change a letter template"

  @S-SCH-13.1
  Scenario: S-SCH-13.1 Run the scheduling reports
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-13 Run the scheduling reports"
    And the scheduler is signed on
    And "appointments cancelled by the clinic and by the patient in my clinics over a range"
    When "I run the cancelled appointment report for one of the two"
    Then "it lists exactly the appointments in PATIENT (#2.98) cancelled that way in those clinics and dates, with the reason"

  @S-SCH-13.2
  Scenario: S-SCH-13.2 Run the scheduling reports
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-13 Run the scheduling reports"
    And the scheduler is signed on
    And "no-shows in my clinics over a range"
    When "I run the no-show report, as totals only or in full"
    Then "it lists them, or counts them, by clinic"

  @S-SCH-13.3
  Scenario: S-SCH-13.3 Run the scheduling reports
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-13 Run the scheduling reports"
    And the scheduler is signed on
    And "a clinic's appointments on a date"
    When "I run the clinic schedule report for that date, one date per page or not"
    Then "it lists the day's appointments in time order with each patient and status"

  @S-SCH-13.4
  Scenario: S-SCH-13.4 Run the scheduling reports
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-13 Run the scheduling reports"
    And the scheduler is signed on
    And "a clinic's checked-in visits over a range"
    When "I run the clinic workload report as a summary by month or a detail by day, with or without the previous year beside it"
    Then "it counts the visits per clinic for each period"

  @S-SCH-13.5
  Scenario: S-SCH-13.5 Run the scheduling reports
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-13 Run the scheduling reports"
    And the scheduler is signed on
    And "appointments past their time in my clinics with no check-in, check-out, cancellation or no-show recorded"
    When "I run the appointments-requiring-action report over the range"
    Then "exactly those are listed"

  @S-SCH-13.6
  Scenario: S-SCH-13.6 Run the scheduling reports
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-13 Run the scheduling reports"
    And the scheduler is signed on
    And "wait-list entries in my clinics"
    When "I run the wait list report over a range of recall, added or removed dates, with or without removed entries, grouped by date, priority, provider, reason or resolution, for one priority or all, in full or as a summary"
    Then "it lists or counts exactly the entries in WAITING LIST (#9009017.1) that match"

  @S-SCH-13.7
  Scenario: S-SCH-13.7 Run the scheduling reports
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-13 Run the scheduling reports"
    And the scheduler is signed on
    And "a patient with future appointments"
    When "I print their future appointments, or their routing slip, wrist band, medication profile or a wellness handout from an appointment"
    Then "the printout is for that patient only"

  @S-SCH-13.8
  Scenario: S-SCH-13.8 Run the scheduling reports
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-SCH-13 Run the scheduling reports"
    And the scheduler is signed on
    And "I hold neither SDZSUP nor SDZMENU"
    When "I open reports"
    Then "none of the scheduling reports is offered to me. ## Signing on (every clinical workflow)"
