# GENERATED by bin/bprm_stubs from docs/bprm/scenarios.tsv (rpms-ux 03976223e8f40fe776d5e43409f1ae7fd7b5d144). Do not edit.
# A scenario leaves this file by being written, with the same tag, in
# features/bprm_twin/w18_*/ and rerunning bin/bprm_stubs.
@bprm_twin @bprm_stub @W18
Feature: W18 Admission, Discharge and Transfer: scenarios no lakeraven-ehr screen drives yet

  @S-ADT-01.2
  Scenario: S-ADT-01.2 Admit a patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-ADT-01 Admit a patient"
    And the admissions clerk is signed on
    And "a required value is missing"
    When "I save the admission"
    Then "it is refused and names the value, and no movement is filed"

  @S-ADT-01.3
  Scenario: S-ADT-01.3 Admit a patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-ADT-01 Admit a patient"
    And the admissions clerk is signed on
    And "an admission date and time in the future"
    When "I save the admission"
    Then "it is refused"

  @S-ADT-01.4
  Scenario: S-ADT-01.4 Admit a patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-ADT-01 Admit a patient"
    And the admissions clerk is signed on
    And "I hold none of the keys that allow moving a patient (DGZADT, DGZNUR, DGZSUP, DGZSYS)"
    When "I open ADT"
    Then "I cannot admit, transfer or discharge"

  @S-ADT-02.2
  Scenario: S-ADT-02.2 Transfer a patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-ADT-02 Transfer a patient"
    And the nurse is signed on
    And "a current inpatient"
    When "I change their room and bed"
    Then "the bed is theirs and their previous bed is free"

  @S-ADT-02.3
  Scenario: S-ADT-02.3 Transfer a patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-ADT-02 Transfer a patient"
    And the nurse is signed on
    And "a current inpatient"
    When "I change their treating specialty or their attending provider with the date and time"
    Then "PATIENT MOVEMENT (#405) holds a treating-specialty movement with the new specialty and provider"

  @S-ADT-02.4
  Scenario: S-ADT-02.4 Transfer a patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-ADT-02 Transfer a patient"
    And the nurse is signed on
    And "a transfer date and time before the admission, or in the future"
    When "I save the transfer"
    Then "it is refused and no movement is filed"

  @S-ADT-03.2
  Scenario: S-ADT-03.2 Discharge a patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-ADT-03 Discharge a patient"
    And the admissions clerk is signed on
    And "a discharge date and time before the admission, or in the future"
    When "I save the discharge"
    Then "it is refused and the patient is still an inpatient"

  @S-ADT-03.3
  Scenario: S-ADT-03.3 Discharge a patient
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-ADT-03 Discharge a patient"
    And the admissions clerk is signed on
    And "a discharge that transfers the patient to another facility"
    When "I save it without naming the facility"
    Then "it is refused and names the facility"

  @S-ADT-04.2
  Scenario: S-ADT-04.2 Correct or cancel a movement
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-ADT-04 Correct or cancel a movement"
    And the admissions clerk is signed on
    And "a discharge entered in error"
    When "I cancel the discharge"
    Then "the patient is a current inpatient again on the ward they were discharged from"

  @S-ADT-04.3
  Scenario: S-ADT-04.3 Correct or cancel a movement
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-ADT-04 Correct or cancel a movement"
    And the admissions clerk is signed on
    And "an admission with the wrong admitting diagnosis or provider"
    When "I change the admission's details"
    Then "the admission movement holds the corrected values and no new movement is filed"

  @S-ADT-05.1
  Scenario: S-ADT-05.1 Complete the chart after discharge
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-ADT-05 Complete the chart after discharge"
    And the him technician is signed on
    And "a discharged patient"
    When "I open an incomplete chart for the stay and record a deficiency against a provider"
    Then "INCOMPLETE CHART (#9009016.1) holds the stay with that provider and deficiency, and the chart is listed as incomplete"

  @S-ADT-05.2
  Scenario: S-ADT-05.2 Complete the chart after discharge
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-ADT-05 Complete the chart after discharge"
    And the him technician is signed on
    And "an incomplete chart with one deficiency"
    When "I record the date the provider resolved it and the date the chart was completed"
    Then "the chart is no longer listed as incomplete"

  @S-ADT-05.3
  Scenario: S-ADT-05.3 Complete the chart after discharge
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-ADT-05 Complete the chart after discharge"
    And the him technician is signed on
    And "I hold none of the incomplete-chart keys (DGZICE, DGZPCC, DGZSUP, DGZSYS)"
    When "I open ADT"
    Then "I cannot open or change an incomplete chart"

  @S-ADT-06.1
  Scenario: S-ADT-06.1 See who is in the house
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-ADT-06 See who is in the house"
    And the nurse is signed on
    And "two patients admitted to a ward and one to another"
    When "I list the current inpatients for the first ward"
    Then "exactly those two are listed, each with their room and bed and attending provider"

  @S-ADT-06.2
  Scenario: S-ADT-06.2 See who is in the house
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-ADT-06 See who is in the house"
    And the nurse is signed on
    And "a patient discharged today"
    When "I list today's discharges"
    Then "the patient is listed with the discharge date and type, and is not on the current inpatient list. ## W19 Benefits and Eligibility Drafts from BPRM 4.0 p6's Benefits module (lakeraven-ehr#565). S-REG-03 (W01) is the front desk's part: enough coverage on file to bill the visit. These are the benefits coordinator's: every kind of coverage, the survey Medicare requires, the order payers are billed in, and the work of getting an uninsured patient covered. Maintaining the insurer, employer and group-plan tables is left to a site-setup workflow"
