# GENERATED by bin/bprm_stubs from docs/bprm/scenarios.tsv (rpms-ux 03976223e8f40fe776d5e43409f1ae7fd7b5d144). Do not edit.
# A scenario leaves this file by being written, with the same tag, in
# features/bprm_twin/w19_*/ and rerunning bin/bprm_stubs.
@bprm_twin @bprm_stub @W19
Feature: W19 Benefits and Eligibility: scenarios no lakeraven-ehr screen drives yet

  @S-BEN-01.2
  Scenario: S-BEN-01.2 See all of a patient's coverage
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-01 See all of a patient's coverage"
    And the benefits coordinator is signed on
    And "a patient with no coverage on file"
    When "I open their coverage"
    Then "the list is empty and I can add coverage"

  @S-BEN-02.1
  Scenario: S-BEN-02.1 Record Medicare, Railroad and Part D coverage
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-02 Record Medicare, Railroad and Part D coverage"
    And the benefits coordinator is signed on
    And "a patient with no Medicare on file"
    When "I record their Medicare beneficiary identifier, the name on the card, and Part A and Part B with effective dates"
    Then "MEDICARE ELIGIBLE (#9000003) holds the patient with that identifier and one eligibility entry per part with its dates"

  @S-BEN-02.2
  Scenario: S-BEN-02.2 Record Medicare, Railroad and Part D coverage
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-02 Record Medicare, Railroad and Part D coverage"
    And the benefits coordinator is signed on
    And "a Medicare beneficiary identifier that is not in the identifier's format"
    When "I save"
    Then "it is refused and nothing is filed"

  @S-BEN-02.3
  Scenario: S-BEN-02.3 Record Medicare, Railroad and Part D coverage
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-02 Record Medicare, Railroad and Part D coverage"
    And the benefits coordinator is signed on
    And "a name on the card that is not `LAST,FIRST MIDDLE`"
    When "I save"
    Then "it is refused and names the format"

  @S-BEN-02.4
  Scenario: S-BEN-02.4 Record Medicare, Railroad and Part D coverage
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-02 Record Medicare, Railroad and Part D coverage"
    And the benefits coordinator is signed on
    And "a Railroad Retirement beneficiary"
    When "I record their number and parts with effective dates"
    Then "RAILROAD ELIGIBLE (#9000005) holds the patient with those parts and dates"

  @S-BEN-02.5
  Scenario: S-BEN-02.5 Record Medicare, Railroad and Part D coverage
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-02 Record Medicare, Railroad and Part D coverage"
    And the benefits coordinator is signed on
    And "a patient with Medicare on file"
    When "I record a Part D plan with its insurer, member number and effective date"
    Then "the Part D eligibility is filed with that insurer and listed with the patient's coverage"

  @S-BEN-02.6
  Scenario: S-BEN-02.6 Record Medicare, Railroad and Part D coverage
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-02 Record Medicare, Railroad and Part D coverage"
    And the benefits coordinator is signed on
    And "a Medicare part recorded in error"
    When "I remove that eligibility entry"
    Then "MEDICARE ELIGIBLE (#9000003) no longer holds it and the other parts are unchanged"

  @S-BEN-03.1
  Scenario: S-BEN-03.1 Record Medicaid coverage
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-03 Record Medicaid coverage"
    And the benefits coordinator is signed on
    And "a patient with no Medicaid on file"
    When "I record their Medicaid number, the name on the card, the state's plan and an eligibility period"
    Then "MEDICAID ELIGIBLE (#9000004) holds the patient with that number, plan and period"

  @S-BEN-03.2
  Scenario: S-BEN-03.2 Record Medicaid coverage
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-03 Record Medicaid coverage"
    And the benefits coordinator is signed on
    And "a plan that requires a rate code"
    When "I save without one"
    Then "it is refused and names the rate code"

  @S-BEN-03.3
  Scenario: S-BEN-03.3 Record Medicaid coverage
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-03 Record Medicaid coverage"
    And the benefits coordinator is signed on
    And "a Medicaid eligibility period that has ended"
    When "I add the new period"
    Then "both periods are on file and only the new one covers today"

  @S-BEN-04.1
  Scenario: S-BEN-04.1 Record private insurance
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-04 Record private insurance"
    And the benefits coordinator is signed on
    And "a patient who holds a policy"
    When "I record the insurer, policy number, coverage type and effective date with the patient as holder"
    Then "POLICY HOLDER holds the policy and PRIVATE INSURANCE ELIGIBLE (#9000006) holds the patient as a member of it"

  @S-BEN-04.2
  Scenario: S-BEN-04.2 Record private insurance
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-04 Record private insurance"
    And the benefits coordinator is signed on
    And "a policy held by the patient's parent"
    When "I add the patient as a member with their relationship to the holder"
    Then "PRIVATE INSURANCE ELIGIBLE (#9000006) holds the patient under that policy with that relationship"

  @S-BEN-04.3
  Scenario: S-BEN-04.3 Record private insurance
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-04 Record private insurance"
    And the benefits coordinator is signed on
    And "a member added to a policy in error"
    When "I remove the member"
    Then "the policy and its other members are unchanged"

  @S-BEN-05.1
  Scenario: S-BEN-05.1 Complete the Medicare Secondary Payer survey
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-05 Complete the Medicare Secondary Payer survey"
    And the benefits coordinator is signed on
    And "a patient with Medicare"
    When "I record the survey with the date it was given, the answers and the signature date"
    Then "MSP PATIENT holds a survey for that date with those answers"

  @S-BEN-05.2
  Scenario: S-BEN-05.2 Complete the Medicare Secondary Payer survey
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-05 Complete the Medicare Secondary Payer survey"
    And the benefits coordinator is signed on
    And "a survey already on file for a date"
    When "I record another for the same date"
    Then "it is refused"

  @S-BEN-05.3
  Scenario: S-BEN-05.3 Complete the Medicare Secondary Payer survey
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-05 Complete the Medicare Secondary Payer survey"
    And the benefits coordinator is signed on
    And "a signature date before the date the survey was given"
    When "I save"
    Then "it is refused"

  @S-BEN-06.1
  Scenario: S-BEN-06.1 Set the order payers are billed in
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-06 Set the order payers are billed in"
    And the benefits coordinator is signed on
    And "a patient with Medicare and a private policy"
    When "I set the private policy first and Medicare second for medical visits from today"
    Then "the patient's sequence for that category and date is filed in that order"

  @S-BEN-06.2
  Scenario: S-BEN-06.2 Set the order payers are billed in
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-06 Set the order payers are billed in"
    And the benefits coordinator is signed on
    And "a sequence on file"
    When "I remove it"
    Then "the patient has no sequence for that category and their coverage is unchanged"

  @S-BEN-07.1
  Scenario: S-BEN-07.1 Record a prior authorization
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-07 Record a prior authorization"
    And the benefits coordinator is signed on
    And "a patient with a private policy"
    When "I record an authorization with the encounter date, insurer, authorization number and date, and the person who authorized it"
    Then "PRIOR AUTHORIZATIONS (#9000046) holds it for the patient with that contact"

  @S-BEN-07.2
  Scenario: S-BEN-07.2 Record a prior authorization
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-07 Record a prior authorization"
    And the benefits coordinator is signed on
    And "an authorization on file"
    When "I add additional authorized days"
    Then "the authorization holds them and its original days are unchanged"

  @S-BEN-07.3
  Scenario: S-BEN-07.3 Record a prior authorization
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-07 Record a prior authorization"
    And the benefits coordinator is signed on
    And "an authorized amount of zero"
    When "I save"
    Then "it is refused"

  @S-BEN-08.1
  Scenario: S-BEN-08.1 Record workers' compensation and third-party liability
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-08 Record workers' compensation and third-party liability"
    And the benefits coordinator is signed on
    And "a patient injured at work"
    When "I record the date of injury, the insurer and the claim number"
    Then "WORKMAN'S COMPENSATION (#9000042) holds the claim for the patient under that date of injury"

  @S-BEN-08.2
  Scenario: S-BEN-08.2 Record workers' compensation and third-party liability
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-08 Record workers' compensation and third-party liability"
    And the benefits coordinator is signed on
    And "a patient injured in an accident where another party is liable"
    When "I record the date of injury and the responsible party"
    Then "THIRD PARTY LIABILITY (#9000041) holds it for the patient under that date of injury"

  @S-BEN-09.1
  Scenario: S-BEN-09.1 Record the guarantor
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-09 Record the guarantor"
    And the benefits coordinator is signed on
    And "a minor patient"
    When "I record a parent as guarantor with an effective date"
    Then "GUARANTOR (#9000043) holds the parent for the patient from that date"

  @S-BEN-09.2
  Scenario: S-BEN-09.2 Record the guarantor
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-09 Record the guarantor"
    And the benefits coordinator is signed on
    And "a guarantor on file"
    When "I end their responsibility and record a new guarantor from the next day"
    Then "both are on file and only the new one is responsible today"

  @S-BEN-10.1
  Scenario: S-BEN-10.1 Work a benefits case
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-10 Work a benefits case"
    And the benefits coordinator is signed on
    And "an uninsured patient referred to me"
    When "I open a case with the date assigned, the reason and myself as the coordinator"
    Then "BENEFIT COORDINATOR CASES (#9000044) holds an open case for the patient assigned to me"

  @S-BEN-10.2
  Scenario: S-BEN-10.2 Work a benefits case
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-10 Work a benefits case"
    And the benefits coordinator is signed on
    And "an open case"
    When "I record an application with its type, the date it was obtained and the date it was submitted"
    Then "PATIENT APPLICATIONS (#9000045) holds the application for the patient with those dates"

  @S-BEN-10.3
  Scenario: S-BEN-10.3 Work a benefits case
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-10 Work a benefits case"
    And the benefits coordinator is signed on
    And "an open case"
    When "I complete it with a date before the date it was assigned"
    Then "it is refused"

  @S-BEN-10.4
  Scenario: S-BEN-10.4 Work a benefits case
    Given this scenario waits on "a lakeraven-ehr screen and steps for S-BEN-10 Work a benefits case"
    And the benefits coordinator is signed on
    And "a completed case and a user without the re-open key (AGZCREOPN)"
    When "they try to re-open it"
    Then "it is refused and the case stays completed"
